Add synonyms
ur-whitelab/joint-chem-space pull request #28
Opened 2023-07-10 16:31 UTC by maykcaldas

2023-07-10 16:34 UTC, maykcaldas commented
Implemented the method. Still need to remove the hard-coded file address, write tests and include this in the usage notebook.

2023-07-10 22:03 UTC, GiaJordan commented
> Implemented the method. Still need to remove the hard-coded file address, write tests and include this in the usage notebook.

@maykcaldas got it, let me know when you're ready for me to take a look

2023-07-10 22:06 UTC, maykcaldas commented
@GiaJordan 
Can you have a quick look to suggest how I can test it? Because we're not uploading the synonyms list, so we can't run the new method in the workflow

2023-07-10 22:53 UTC, GiaJordan commented
@maykcaldas in its current form it wouldn't be the easiest to test. We could create a dummy test `.csv` file with synonyms and pass that path in if we wanted to, but I don't think that's what we've done elsewhere in this codebase. 

What we have done is write tests that use the `.gz` file and only run them locally, and then skip them on gh actions. This isn't the best but it'll work for now, and we could go back later and refactor so it's easier to test

2023-07-11 17:33 UTC, maykcaldas commented
Great, @GiaJordan
I implemented a test to run locally. Please, feel free to review it when you have time.

2023-07-13 16:49 UTC, GiaJordan requested changes

2023-07-13 16:49 UTC, GiaJordan commented on tests/test_dataset_builder.py
> +    @pytest.mark.skipif(IN_GITHUB_ACTIONS, reason="Synonyms file is not available in GitHub")
Test looks good, could we just update the mark on `test_instantiate_DB_from_file` to match this one as well?

2023-07-13 17:24 UTC, GiaJordan approved these changes

2023-07-13 17:24 UTC, merged